version: '3.4'

volumes:
  local_postgres_data: {}

services:
  coreapi:
    image: ${DOCKER_REGISTRY-}coreapi
    build:
      context: .
      dockerfile: CoreApi/Dockerfile
    depends_on:
      - db
  
  db:
    image: postgres:11.1