version: '3.4'

services:
  coreapi:
    image: ${DOCKER_REGISTRY-}coreapi
    build:
      context: .
      dockerfile: CoreApi/Dockerfile
    depends_on:
      - db
  
  db:
    image: postgres:11.1
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db

volumes:
  db-data:
  pgadmin-data: